default: &default
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["AWS_REGION"] %>
  # identity_pool_id: <%= ENV["AWS_IDENTITY_POOL_ID"] %>
  # user_pool_id: <%= ENV["USER_POOL_ID"] %>
  # client_id: <%= ENV["CLIENT_ID"] %>


development:
  <<: *default
  endpoint: http://localhost:8000

test:
  <<: *default
  endpoint: http://localhost:8000

production:
  <<: *default